# Generated by Django 4.2.1 on 2023-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(default=0)),
                ('comp_name', models.CharField(default='', max_length=300)),
                ('designation', models.CharField(default='', max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
